# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: deploy workflow
on:
   workflow_call:
    inputs:
      environment:
        required: true
        type: string
   
      
jobs:
  Deployment:
    name: Deployment
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
        - name: Show default environment variables
          run: |
            echo "The url is: ${{ secrets.DATAVERSEENVURL }}"   # reference the default environment variables
 
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 8.0.x
        - name: Download tool artifact
          uses: actions/download-artifact@v4
          with:
            name: configurationmigrationtool
            path: '${{ github.workspace }}/configurationmigrationtool'
        - name: Download data artifact
          uses: actions/download-artifact@v4
          with:
            name: data
            path: '${{ github.workspace }}/data'
        - name: Replace tokens
          uses: cschleiden/replace-tokens@v1
          with:
            tokenPrefix: '${'
            tokenSuffix: '}$'
            files: '["**/*.json"]'
          env:
            DATAVERSECLIENTID: ${{ secrets.DATAVERSECLIENTID }}
            DATAVERSECLIENTSECRET: ${{ secrets.DATAVERSECLIENTSECRET  }}
            DATAVERSEENVURL: ${{ secrets.DATAVERSEENVURL }}
        - name: import configuration data
          run: |
            cd ${{ github.workspace }}/configurationmigrationtool
            dotnet Dataverse.ConfigurationMigrationTool.Console.dll import --schema "../data/data_schema.xml" --data "../data/data.xml"
          env:
            DOTNET_ENVIRONMENT: Production
            environment: Production

        



  
    
  